### PR TITLE
Benn's Static Review

### PR DESCRIPTION
**Pull request by bcurby**
Static review of Benn's files using the following style guidelines:

•	All class, variable, and method names should be meaningful. E.g. for a method that lists books, the name should be listBooks(), rather than lbk().
•	Class, variable, and method names should not use abbreviations, except for common acronyms (e.g. html rather than HyperText Markup Language)
•	Class names should start with a capital and use CamelBack.
•	Variable names should be nouns or noun phrases, start with a lower case letter and use camelBack.
•	Method names should be verbs or verb phrases, start with a lower case letter and useCamelBack.
•	Indentation increments should be 4 characters.
•	All variables and operators MUST be separated by white space. E.g.:
Not:
a=b+c+d;
Rather:
a = b + c + d;
•	Anywhere curly brackets MAY be used, they MUST be used. E.g.:
Not:
if (condition)
some single line of optional code;
further non optional code;
Rather:
if (condition) {
some single line of optional code;
}

•	Random rules that must also be enforced:
•	There should be no method calls within argument lists of any method calls.
•	No calculations within Boolean expressions
•	No negated Boolean variable names or negated Boolean methods. E.g. ‘isError’ rather than ‘isNoError’.
•	Singletons should return their sole instance through a method called getInstance()
•	All class and method declarations should be separated from the previous block of code by 2 space lines.

### CODE REVIEW

**Review by lukexjohnson — CHANGES_REQUESTED** [review]
BorrowBookControl

D1: (L16) Remove unecessary whitespace to match other empty lines

D2: Multiple Classes;

BorrowBookControl (L22) Change library.getInstance ---> Library.getInstance

FixBookControl (L13) Change library.getInstance ---> Library.getInstance

PayFineControl (L13) Change library.getInstance ---> Library.getInstance

-------------------

BorrowBookUI

D3: (L4-108) Tabs need to be changed to 4 spaces

D4: (L25, 43, 100, 102, 107) Remove tab after brace/end of statement 

D5: (L32, 37, 40, 42, 44, 63, 68, 78, 83, 93, 97) Remove unrequired tabs on empty lines 

D6: (L38) method name run --> runBorrowBook 

D7: (L22) method name input--> takeInput

D8: (L28) method name output --> displayOutputMessage

D9: (L106) method name display --> displayMessage

-------------------
Library

0 Defects for this class - great job.

-------------------
Member 

0 Defects for this class - great job.

**Comment by bcurby** [comment]
D1 - D2: BorrowBookControl
All fixed and pushed.

**Comment by bcurby** [comment]
D3 - D9 BorrowBookUI
All fixed and pushed.

Note:
screen shot 2018-08-17 at 5 02 44 pm
These were all fixed and pushed up as part of commit D3.

**Comment by bcurby** [comment]
All defects (D1 - D9) fixed and commits made/pushed.
Awaiting confirmation.

**Comment by lukexjohnson** [comment]
All issues amended ready for merge

**Comment by Millsy66** [comment]
Well done. Static review ready to merge.

**Pull request merged**
